// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qslijvyhvyvqlowdxvdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzbGlqdnlodnl2cWxvd2R4dmR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODc2NjcsImV4cCI6MjA2NTU2MzY2N30.HY9E1aK_YE63CKKZ4rbHTul8KCGaT83TnZam54XtqsE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});